export const aboutObj = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Aka unicorn employee',
    headLine: 'A complete professional',
    description: 'Industrial Mechanics Technician, Materials Engineer, selft-taught Developer & Designer. Methodic problem-solver, empathetic team-player, intelligent creator. Versatile and self-driven.',
    imgStart: true,
    img: require('../../images/undraw_both_sides_hbv3.svg').default,
    alt: 'About',
    darkText: true,
    button: 'portfolio',
    buttonDesc: 'See my work',
    dark: false,
    primary: false,
    big: true,
}

export const portfolioObj = {
    id: 'portfolio',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Results and creations',
    headLine: 'From engineering projects to coding front-end and designing prototypes',
    description: 'Hyundai Motor Company, BMW Group, Bavarian Ministry for Digital Affairs, Digital Product School, UnternehmerTUM.',
    imgStart: false,
    img: require('../../images/undraw_in_progress_ql66.svg').default,
    alt: 'portfolio',
    darkText: false,
    button: 'myportfolio',
    buttonDesc: 'Check my portfolio',
    dark: true,
    primary: true,
    big: true,
}

export const contactObj = {
    id: 'contact',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Let's talk",
    headLine: "I'm willing to make a difference",
    description: 'natashalivieira@gmail.com | +49 177454 1316',
    imgStart: true,
    img: require('../../images/undraw_things_to_say_ewwb.svg').default,
    alt: 'contact',
    darkText: true,
    button: 'about',
    buttonDesc: 'Get to know me',
    big: true,
}